import { Contractor } from "./types";

export { STATES, SERVICES } from "./types";

export const CONTRACTORS: Contractor[] = [
  {
    name: "1st Green Home",
    address: {
      line1: "10630 Riggs Hill Rd. Unit A",
      line2: "",
      city: "Jessup",
      state: "MD",
      zipCode: "20794",
    },
    phoneNumber: "4432169169",
    statesServed: ["MD", "DC"],
    services: ["Energy Audit", "Weatherization", "Water Heater"],
  },
  {
    name: "Accurate Insulation, LLC",
    address: {
      line1: "15121 Marlboro Pike",
      line2: "",
      city: "Upper Marlboro",
      state: "MD",
      zipCode: "20772",
    },
    phoneNumber: "3016276506",
    statesServed: ["MD", "VA"],
    services: ["Energy Audit", "Weatherization", "Water Heater"],
  },
  {
    name: "Advanced Green Home Solutions",
    address: {
      line1: "1125 West Street",
      line2: "Suite 421",
      city: "Annapolis",
      state: "MD",
      zipCode: "21401",
    },
    phoneNumber: "4435756592",
    statesServed: ["MD", "VA", "DC"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "AHS Inc.",
    address: {
      line1: "507 Mullin Lane",
      line2: "",
      city: "Bowie",
      state: "MD",
      zipCode: "20175",
    },
    phoneNumber: "3013995119",
    statesServed: ["MD", "DC"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "American Home Builders Inc.",
    address: {
      line1: "2036 Tred Avon Rd.",
      line2: "",
      city: "Essex",
      state: "MD",
      zipCode: "21221",
    },
    phoneNumber: "4103910500",
    statesServed: ["MD", "VA"],
    services: ["Weatherization", "Water Heater"],
  },
  {
    name: "American Home Performance, LLC",
    address: {
      line1: "502 East Franklin Ave",
      line2: "",
      city: "Silver Spring",
      state: "MD",
      zipCode: "20901",
    },
    phoneNumber: "2407437115",
    statesServed: ["MD", "VA", "DC"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "Atlas Home Energy Solutions",
    address: {
      line1: "5108 Pegasus Ct",
      line2: "Suite A",
      city: "Frederick",
      state: "MD",
      zipCode: "21704",
    },
    phoneNumber: "3013645055",
    statesServed: ["MD", "DC"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "Building Energy Pros",
    address: {
      line1: "PO Box 4225",
      line2: "",
      city: "West McLean",
      state: "VA",
      zipCode: "22103",
    },
    phoneNumber: "2402525292",
    statesServed: ["VA", "MD"],
    services: ["Energy Audit", "Weatherization", "Water Heater"],
  },
  {
    name: "C.A.R.E. Property Services, Inc.",
    address: {
      line1: "12507 Sunset Avenue",
      line2: "Unit #30",
      city: "Ocean City",
      state: "MD",
      zipCode: "21842",
    },
    phoneNumber: "7176343060",
    statesServed: ["MD", "VA", "DC"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "Comfort Kings",
    address: {
      line1: "3640 Dalrymple Rd",
      line2: "",
      city: "Chesapeake Beach",
      state: "MD",
      zipCode: "20732",
    },
    phoneNumber: "6674733011",
    statesServed: ["MD", "DC"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "Complete Home Solutions, LLC",
    address: {
      line1: "235 W Bay Front Road",
      line2: "",
      city: "Lothian",
      state: "MD",
      zipCode: "20711",
    },
    phoneNumber: "4108671202",
    statesServed: ["MD"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "Constellation Home",
    address: {
      line1: "1409-A Tangier Dr",
      line2: "",
      city: "Middle River",
      state: "MD",
      zipCode: "21220",
    },
    phoneNumber: "8882434663",
    statesServed: ["MD", "VA"],
    services: ["Energy Audit", "Weatherization", "Water Heater"],
  },
  {
    name: "CroppMetCalfe",
    address: {
      line1: "8421 Hilltop Road",
      line2: "",
      city: "Fairfax",
      state: "VA",
      zipCode: "22031",
    },
    phoneNumber: "7036988855",
    statesServed: ["VA", "MD"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "Devere Insulation Home Performance",
    address: {
      line1: "7501 Resource Ct",
      line2: "",
      city: "Curtis Bay",
      state: "MD",
      zipCode: "21226",
    },
    phoneNumber: "4437701111",
    statesServed: ["MD", "DC"],
    services: ["Energy Audit", "Weatherization", "Water Heater"],
  },
  {
    name: "EcoMize USA, LLC",
    address: {
      line1: "126 Church Lane",
      line2: "",
      city: "Cockeysville",
      state: "MD",
      zipCode: "21030",
    },
    phoneNumber: "4104467283",
    statesServed: ["MD", "VA"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "EDGE Energy",
    address: {
      line1: "6854 Distribution Drive",
      line2: "",
      city: "Beltsville",
      state: "MD",
      zipCode: "20705",
    },
    phoneNumber: "8885863343",
    statesServed: ["MD"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "Efficient Home, LLC",
    address: {
      line1: "3905 National Drive",
      line2: "Suite 105",
      city: "Burtonsville",
      state: "MD",
      zipCode: "20866",
    },
    phoneNumber: "3014767680",
    statesServed: ["MD", "VA", "DC"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "Elysian Energy, LLC",
    address: {
      line1: "14300 Cherry Lane Court",
      line2: "Suite 214",
      city: "Laurel",
      state: "MD",
      zipCode: "20707",
    },
    phoneNumber: "2404240523",
    statesServed: ["MD", "DC"],
    services: ["Energy Audit", "Weatherization", "Water Heater"],
  },
  {
    name: "Ener G, LLC",
    address: {
      line1: "3900 Briars Rd",
      line2: "",
      city: "Olney",
      state: "MD",
      zipCode: "20832",
    },
    phoneNumber: "3013631148",
    statesServed: ["MD", "VA"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "Energy Efficiency Experts",
    address: {
      line1: "9327 Fraser Avenue",
      line2: "",
      city: "Silver Spring",
      state: "MD",
      zipCode: "20910",
    },
    phoneNumber: "2025579200",
    statesServed: ["MD", "DC"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "Future Green Services",
    address: {
      line1: "2020 F St NW",
      line2: "Suite 524",
      city: "Washington",
      state: "DC",
      zipCode: "20006",
    },
    phoneNumber: "4434962655",
    statesServed: ["DC", "MD"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "Green-Energy 360",
    address: {
      line1: "5514 Hayloft Court",
      line2: "",
      city: "Frederick",
      state: "MD",
      zipCode: "21703",
    },
    phoneNumber: "2403976901",
    statesServed: ["MD", "VA"],
    services: ["Energy Audit", "Weatherization", "Water Heater"],
  },
  {
    name: "Greenworks Systems, LLC",
    address: {
      line1: "9124 Belair Rd",
      line2: "",
      city: "Perry Hall",
      state: "MD",
      zipCode: "21236",
    },
    phoneNumber: "4436043161",
    statesServed: ["MD", "DC"],
    services: ["Energy Audit", "Weatherization"],
  },
  {
    name: "Home Energy HERO, LLC",
    address: {
      line1: "PO Box 121",
      line2: "",
      city: "Clarksville",
      state: "MD",
      zipCode: "21209",
    },
    phoneNumber: "8884904376",
    statesServed: ["MD"],
    services: ["Energy Audit", "Weatherization", "Water Heater"],
  },
  {
    name: "Home Energy Medics",
    address: {
      line1: "817 22nd Street S",
      line2: "",
      city: "Arlington",
      state: "VA",
      zipCode: "22202",
    },
    phoneNumber: "7034475379",
    statesServed: ["VA", "MD"],
    services: ["Energy Audit", "Weatherization", "HVAC"],
  },
  {
    name: "Home Energy Saving Solutions",
    address: {
      line1: "5208 Ernie Lane",
      line2: "",
      city: "Kensington",
      state: "MD",
      zipCode: "20895",
    },
    phoneNumber: "3018428818",
    statesServed: ["MD", "VA"],
    services: ["Energy Audit", "Weatherization"],
  },
  {
    name: "Hometrust Remodeling",
    address: {
      line1: "8345 Sperry Court",
      line2: "",
      city: "Laurel",
      state: "MD",
      zipCode: "20723",
    },
    phoneNumber: "3019576532",
    statesServed: ["MD", "DC"],
    services: ["Energy Audit", "Weatherization"],
  },
  {
    name: "Lumeco Energy",
    address: {
      line1: "8643 Cherry Ln",
      line2: "",
      city: "Laurel",
      state: "MD",
      zipCode: "20707",
    },
    phoneNumber: "3018527663",
    statesServed: ["MD", "VA", "DC"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "Potomac View Energy, Inc.",
    address: {
      line1: "7520 Main Street",
      line2: "Suite 201",
      city: "Sykesville",
      state: "MD",
      zipCode: "21784",
    },
    phoneNumber: "4432776307",
    statesServed: ["MD"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "Shepherd Design and Construction",
    address: {
      line1: "16701 Melford Blvd",
      line2: "Ste. 400",
      city: "Bowie",
      state: "MD",
      zipCode: "20715",
    },
    phoneNumber: "2404628927",
    statesServed: ["MD", "VA"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
  {
    name: "SM Mechanical LLC",
    address: {
      line1: "7110 Golden Ring Rd",
      line2: "",
      city: "Essex",
      state: "MD",
      zipCode: "21221",
    },
    phoneNumber: "4105985515",
    statesServed: ["MD", "DC"],
    services: ["Energy Audit", "Weatherization", "Water Heater", "HVAC"],
  },
];
